global:
  domain: consul
  datacenter: minidc    # minikube环境，否则 datacenter: dc

server:
  replicas: 1
  bootstrapExpect: 1

client:
  enabled: true
  grpc: true

ui:
  enabled: true

connectInject:
  enabled: true

syncCatalog:
  enabled: true
